sudo: false

language: node_js

node_js:
  - 10

cache: npm

branches:
  only:
    - blog

before_install:
  - npm install -g hexo
  - npm install -g hexo-cli

install:
  - npm install

before_script:
  - git config --global user.name 'huanglei'
  - git config --global user.email 'code.huanglei@gmail.com'
  - sed -i "s/gh_token/${GH_TOKEN}/g" _config.yml

script:
  - hexo clean
  - hexo generate

after_success:
  - hexo deploy
