menu:
  Home: /
  GoLang: /categories/golang/
  Tools: https://huanglei.org/chrome-rabbit/dist
  GitHub: https://github.com/ihuanglei

# gitment
gitment: false
gitment_owner:
gitment_repo:
gitment_client_id:
gitment_client_secret:

# gitalk
gitalk: false
gitalk_owner:
gitalk_admin: []
gitalk_repo:
gitalk_client_id:
gitalk_client_secret:

# valine comment
valine: false
leancloud_id:
leancloud_key:

# disqus comment
disqus: false
disqus_shortname:

# google analytics
googleTrackId:

# whether to show read more button when showing article in excerpt in main page
read_more: false

# baidu analytics
baidu_analytics: 9f876c77a5ba35ad24ed7e32df74db58